/*
 * Simple DDS RTPS Pub Sub with the Sensors data exchange.
 */

module Sensors {

  @topic
  struct SoundingData {
    @key long sensor_id;
    double depthBelowTransducer;
    double depthBelowKeel;
    boolean validity;
  };
};
